version: '3.1'

services:

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  apache-php:
    container_name: apache-php
    build: .
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
    ports:
      - 8082:80
    
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8083:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M